# [Services]
apiVersion: v1
kind: Service
metadata:
  name: huenei-clean-svc
spec:
  ports:
  - port: 8082
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: huenei-clean
    tier: backend
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: huenei-clean
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huenei-clean
  template:
    metadata:
      labels:
        app: huenei-clean
        tier: backend
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      # [APP]
      - name: huenei-clean
        image: gcr.io/flowing-sign-277615/huenei-clean:latest
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
          limits:
            cpu: "200m"
            memory: "1000Mi" 
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 160
          periodSeconds: 60
          timeoutSeconds: 10       
        #[env-vars]
        env:
        - name: SFTP_HOST
          value: "34.69.58.88"
        - name: SFTP_USER
          value: "kervin"
        - name: SFTP_PSWD
          value: Picky2020
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json