/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.huenei;

import org.junit.Test;

import com.huenei.CleansingApplication;

import static org.junit.Assert.*;

public class CleansingApplicationTest {
    @Test public void testSomeLibraryMethod() {
        CleansingApplication classUnderTest = new CleansingApplication();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
